# Generated by Django 3.2.3 on 2021-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('birthday', models.DateTimeField()),
                ('birth_place', models.CharField(max_length=35)),
                ('create_card_place', models.CharField(max_length=35)),
                ('serial_card', models.CharField(max_length=35)),
                ('nin', models.CharField(max_length=12)),
                ('home_phone', models.CharField(max_length=35)),
                ('home_code', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('father_father_name', models.CharField(max_length=50)),
                ('father_nin', models.CharField(max_length=12)),
                ('father_create_card_place', models.CharField(max_length=35)),
                ('father_education', models.CharField(max_length=35)),
                ('father_phone', models.CharField(max_length=35)),
                ('father_work', models.CharField(max_length=35)),
                ('father_birth', models.DateTimeField()),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_father_name', models.CharField(max_length=50)),
                ('mother_nin', models.CharField(max_length=12)),
                ('mother_create_card_place', models.CharField(max_length=35)),
                ('mother_education', models.CharField(max_length=35)),
                ('mother_phone', models.CharField(max_length=35)),
                ('mother_work', models.CharField(max_length=35)),
                ('mother_birth', models.DateTimeField()),
                ('telegram_phone', models.CharField(max_length=35)),
            ],
        ),
    ]
