# Generated by Django 3.2.3 on 2021-06-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='e_place',
            field=models.CharField(choices=[('مهد دردانه', 'مهد دردانه'), ('پیش دبستانی یگانه', 'پیش دبستانی یگانه')], default='مهد دردانه', max_length=30),
        ),
    ]
