# Generated by Django 3.2.4 on 2022-04-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userprofile_e_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='father_serial_card',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mother_serial_card',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='serial_card',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Bimeh',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Child',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Children',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Farhangi',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Fatherseri',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Fatherserial',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Hand',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Motherseri',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Motherserial',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Serialcard',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Sericard',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Shahid',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Talagh',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
