# Generated by Django 3.2.3 on 2022-05-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220410_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
